openapi: 3.1.0
info:
  title: Fitbit Web API (Legacy)
  version: 0.5.0
  license:
    name: Fitbit API Terms
    url: https://dev.fitbit.com/legal/platform-terms-of-service/
  description: OpenAPI specification for the Fitbit Web API (Legacy). The official Fitbit documentation states that the Fitbit Web API (Legacy) will be deprecated in September 2026.
servers:
  - url: https://api.fitbit.com
security:
  - fitbitOAuth: []
paths:
  /1/user/{user-id}/activities/active-zone-minutes/date/{date}/{period}.json:
    get:
      operationId: activeZoneMinutesTimeseriesGetGetAzmTimeSeriesByDate1UserUserIdActivitiesActiveZoneMinutesDateDatePeriodJson
      summary: Get AZM Time Series by Date
      description: This endpoint returns the daily summary values over a period of time by specifying a date and time period.
      tags:
        - Active-Zone-Minutes-Timeseries
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/active-zone-minutes-timeseries/get-azm-timeseries-by-date/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/goals/{period}.json:
    post:
      operationId: activityPostCreateActivityGoal1UserUserIdActivitiesGoalsPeriodJson
      summary: Create Activity Goal
      description: |-
        Creates or updates a user's daily or weekly activity goal.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/create-activity-goals/
      security:
        - fitbitOAuth:
            - activity
    get:
      operationId: activityGetGetActivityGoals1UserUserIdActivitiesGoalsPeriodJson
      summary: Get Activity Goals
      description: |-
        Retrieves a user's current daily or weekly activity goals.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/get-activity-goals/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities.json:
    post:
      operationId: activityPostCreateActivityLog1UserUserIdActivitiesJson
      summary: Create Activity Log
      description: Creates a log entry containing the Fitbit user's activity or private custom activity.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/create-activity-log/
      security:
        - fitbitOAuth:
            - activity
    get:
      operationId: activityGetGetLifetimeStats1UserUserIdActivitiesJson
      summary: Get Lifetime Stats
      description: Retrieves the user's activity statistics.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/get-lifetime-stats/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/favorite/{activity-id}.json:
    post:
      operationId: activityPostCreateFavoriteActivity1UserUserIdActivitiesFavoriteActivityIdJson
      summary: Create Favorite Activity
      description: Adds the activity with the given ID to user's list of favorite activities.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/create-favorite-activity/
      security:
        - fitbitOAuth:
            - activity
    delete:
      operationId: activityDeleteDeleteFavoriteActivity1UserUserIdActivitiesFavoriteActivityIdJson
      summary: Delete Favorite Activity
      description: Removes the activity from a user’s list of favorite activities.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/delete-favorite-activity/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/{activity-log-id}.json:
    delete:
      operationId: activityDeleteDeleteActivityLog1UserUserIdActivitiesActivityLogIdJson
      summary: Delete Activity Log
      description: Deletes a user’s activity log entry with the given ID.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/delete-activity-log/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/list.json:
    get:
      operationId: activityGetGetActivityLogList1UserUserIdActivitiesListJson
      summary: Get Activity Log List
      description: Retrieves a list of a user's activity log entries before or after a given day.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/get-activity-log-list/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/{log-id}.tcx:
    get:
      operationId: activityGetGetActivityTcx1UserUserIdActivitiesLogIdTcx
      summary: Get Activity TCX
      description: The Training Center XML (TCX) is a data exchange format that contains GPS, heart rate, and lap data. This endpoint retrieves the details of a user's location using GPS and heart rate data during a logged exercise.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/get-activity-tcx/
      security:
        - fitbitOAuth:
            - activity
  /1/activities/{activity-id}.json:
    get:
      operationId: activityGetGetActivityType1ActivitiesActivityIdJson
      summary: Get Activity Type
      description: Retrieves the details for a single activity from the Fitbit activities database in the format requested. If available, activity level details will display.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/get-activity-type/
      security:
        - fitbitOAuth:
            - activity
  /1/activities.json:
    get:
      operationId: activityGetGetAllActivityTypes1ActivitiesJson
      summary: Get All Activity Types
      description: Retrieves a list of all valid Fitbit public activities and the private, user-created activities from the Fitbit activities database in the format requested. If available, activity level details will display.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/get-all-activity-types/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/date/{date}.json:
    get:
      operationId: activityGetGetDailyActivitySummary1UserUserIdActivitiesDateDateJson
      summary: Get Daily Activity Summary
      description: Retrieves a summary and list of a user’s activities and activity log entries for a given day.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/get-daily-activity-summary/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/favorite.json:
    get:
      operationId: activityGetGetFavoriteActivities1UserUserIdActivitiesFavoriteJson
      summary: Get Favorite Activities
      description: Retrieves a list of a user's favorite activities.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/get-favorite-activities/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/frequent.json:
    get:
      operationId: activityGetGetFrequentActivities1UserUserIdActivitiesFrequentJson
      summary: Get Frequent Activities
      description: Retrieves a list of a user's frequent activities.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/get-frequent-activities/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/recent.json:
    get:
      operationId: activityGetGetRecentActivityTypes1UserUserIdActivitiesRecentJson
      summary: Get Recent Activity Types
      description: Retrieves a list of a user's recent activities types logged with some details of the last activity log of that type.
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/get-recent-activity-types/
      security:
        - fitbitOAuth:
            - activity
  /1/user/-/activities/{logId}/workout-summary:
    get:
      operationId: activityGetGetWorkoutSummary1UserActivitiesLogidWorkoutSummary
      summary: Get Workout Summary
      description: 'Exposes the ground contact time and step cadence collected during Run workouts:'
      tags:
        - Activity
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity/get-workout-summary/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/{resource-path}/date/{start-date}/{end-date}.json:
    get:
      operationId: activityTimeseriesGetGetActivityTimeSeriesByDateRange1UserUserIdActivitiesResourcePathDateStartDateEndDateJson
      summary: Get Activity Time Series by Date Range
      description: Retrieves the activity data for a given resource over a period of time by specifying a date range. The response will include only the daily summary values.
      tags:
        - Activity-Timeseries
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/activity-timeseries/get-activity-timeseries-by-date-range/
      security:
        - fitbitOAuth:
            - activity
  /oauth2/token:
    post:
      operationId: authorizationPostClientCredentialsGrantFlowOauth2Token
      summary: Client Credentials Grant Flow
      description: |-
        The /oauth2/token endpoint can do the following: Exchange the authorization code for the initial access token and refresh token (See OAuth2 Token ). This process is required when using the Authorization Code Grant Flow [with PKCE]. Obtain a new access token and refresh token when the existing access token has expired (See Refresh Token ). Initiate the Client Credentials authorization flow (See Client Credentials ).

        Fitbit follows the OAuth 2.0 Client Credentials flow as specified in RFC 6749 . This authorization flow is used with specific Fitbit API endpoints related to business operations. It is not supported by the public Web APIs to retrieve Fitbit user data.

        The Client Credentials Grant flow has the following steps:

        The application sends a request to https ://api.fitbit.com/oauth2/token with its client_id and client_secret; and Fitbit authenticates your application and issues an access token.
      tags:
        - Authorization
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/authorization/client-credentials/
  /1.1/oauth2/introspect:
    post:
      operationId: authorizationPostIntrospect11Oauth2Introspect
      summary: Introspect
      description: Allows the application to retrieve the active state of an OAuth 2.0 token. This endpoint conforms to RFC 7662 .
      tags:
        - Authorization
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/authorization/introspect/
  /oauth2/revoke:
    post:
      operationId: authorizationPostRevokeTokenOauth2Revoke
      summary: Revoke Token
      description: |-
        Used to disable a user's authorization for an application. The revoke endpoint, specifying either the access token or refresh token, will remove the user's authorizations and all associated tokens. This endpoint conforms to RFC 7009 .

        Revoking the access token or refresh token will provide the same result. When the token is revoked, all tokens are revoked for that user. If an application has multiple sessions (web, mobile, etc.) for the same user, the revocation will remove all sessions (web, mobile, etc.) associated with that user.

        In addition, a revocation request can be made for tokens used by public clients. The Authorization header is not used. Instead, the public client's client_id and associated token will need to be specified as parameters in the revocation request.
      tags:
        - Authorization
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/authorization/revoke-token/
  /1/user/-/health/metrics/glucose/values/{startDate}/{endDate}.json:
    get:
      operationId: bloodGlucoseGetGetBloodGlucoseByInterval1UserHealthMetricsGlucoseValuesStartdateEnddateJson
      summary: Get Blood Glucose by Interval
      description: Retrieves the user's daily, min, max, sum and average values of blood glucose levels within an interval.
      tags:
        - Blood-Glucose
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/blood-glucose/get-blood-glucose-by-interval/
      security:
        - fitbitOAuth:
            - blood_glucose
  /1/user/{user-id}/body/log/fat/goal.json:
    post:
      operationId: bodyPostCreateBodyFatGoal1UserUserIdBodyLogFatGoalJson
      summary: Create Body Fat Goal
      description: Create or update a user's body fat goal.
      tags:
        - Body
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/body/create-bodyfat-goal/
      security:
        - fitbitOAuth:
            - weight
  /1/user/{user-id}/body/log/fat.json:
    post:
      operationId: bodyPostCreateBodyFatLog1UserUserIdBodyLogFatJson
      summary: Create Body Fat Log
      description: Creates a body fat log entry.
      tags:
        - Body
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/body/create-bodyfat-log/
      security:
        - fitbitOAuth:
            - weight
  /1/user/{user-id}/body/log/weight/goal.json:
    post:
      operationId: bodyPostCreateWeightGoal1UserUserIdBodyLogWeightGoalJson
      summary: Create Weight Goal
      description: Creates or updates a user's weight goal.
      tags:
        - Body
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/body/create-weight-goal/
      security:
        - fitbitOAuth:
            - weight
  /1/user/{user-id}/body/log/weight.json:
    post:
      operationId: bodyPostCreateWeightLog1UserUserIdBodyLogWeightJson
      summary: Create Weight Log
      description: Creates a weight log entry
      tags:
        - Body
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/body/create-weight-log/
      security:
        - fitbitOAuth:
            - weight
  /1/user/{user-id}/body/log/fat/{body-fat-log-id}.json:
    delete:
      operationId: bodyDeleteDeleteBodyFatLog1UserUserIdBodyLogFatBodyFatLogIdJson
      summary: Delete Body Fat Log
      description: Deletes a body fat log entry
      tags:
        - Body
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/body/delete-bodyfat-log/
      security:
        - fitbitOAuth:
            - weight
  /1/user/{user-id}/body/log/weight/{weight-log-id}.json:
    delete:
      operationId: bodyDeleteDeleteWeightLog1UserUserIdBodyLogWeightWeightLogIdJson
      summary: Delete Weight Log
      description: Deletes a Weight log entry
      tags:
        - Body
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/body/delete-weight-log/
      security:
        - fitbitOAuth:
            - weight
  /1/user/{user-id}/body/log/{goal-type}/goal.json:
    get:
      operationId: bodyGetGetBodyGoals1UserUserIdBodyLogGoalTypeGoalJson
      summary: Get Body Goals
      description: Retrieves a user's body fat and weight goals.
      tags:
        - Body
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/body/get-body-goals/
      security:
        - fitbitOAuth:
            - weight
  /1/user/{user-id}/body/log/fat/date/{date}.json:
    get:
      operationId: bodyGetGetBodyFatLog1UserUserIdBodyLogFatDateDateJson
      summary: Get Body Fat Log
      description: Retrieves a list of all user's body fat log entries for a given date.
      tags:
        - Body
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/body/get-bodyfat-log/
      security:
        - fitbitOAuth:
            - weight
  /1/user/{user-id}/body/log/weight/date/{date}.json:
    get:
      operationId: bodyGetGetWeightLog1UserUserIdBodyLogWeightDateDateJson
      summary: Get Weight Log
      description: Retrieves a list of all user's weight log entries for a given date.
      tags:
        - Body
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/body/get-weight-log/
      security:
        - fitbitOAuth:
            - weight
  /1/user/{user-id}/body/{resource}/date/{begin-date}/{end-date}.json:
    get:
      operationId: bodyTimeseriesGetGetBodyTimeSeriesByDateRange1UserUserIdBodyResourceDateBeginDateEndDateJson
      summary: Get Body Time Series by Date Range
      description: Retrieves a list of all user's bmi, body fat, or weight for a given date range.
      tags:
        - Body-Timeseries
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/body-timeseries/get-body-timeseries-by-date-range/
      security:
        - fitbitOAuth:
            - weight
  /1/user/{user-id}/body/log/fat/date/{start-date}/{end-date}.json:
    get:
      operationId: bodyTimeseriesGetGetBodyFatTimeSeriesByDateRange1UserUserIdBodyLogFatDateStartDateEndDateJson
      summary: Get Body Fat Time Series by Date Range
      description: Retrieves a list of all user's body fat log entries for a given date range.
      tags:
        - Body-Timeseries
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/body-timeseries/get-bodyfat-timeseries-by-date-range/
      security:
        - fitbitOAuth:
            - weight
  /1/user/{user-id}/body/log/weight/date/{start-date}/{end-date}.json:
    get:
      operationId: bodyTimeseriesGetGetWeightTimeSeriesByDateRange1UserUserIdBodyLogWeightDateStartDateEndDateJson
      summary: Get Weight Time Series by Date Range
      description: Retrieves a list of all user's weight log entries for a given date range.
      tags:
        - Body-Timeseries
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/body-timeseries/get-weight-timeseries-by-date-range/
      security:
        - fitbitOAuth:
            - weight
  /1/user/{user-id}/br/date/{date}.json:
    get:
      operationId: breathingRateGetGetBreathingRateSummaryByDate1UserUserIdBrDateDateJson
      summary: Get Breathing Rate Summary by Date
      description: |-
        This endpoint returns average breathing rate data for a single date. Breathing Rate data applies specifically to a user’s “main sleep,” which is the longest single period of time during which they were asleep on a given date.

        The measurement is provided at the end of a period of sleep. The data returned can and often does reflect a sleep period that began the day before. For example, if you request a daily breathing rate for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user started to sleep.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Breathing-Rate
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/breathing-rate/get-br-summary-by-date/
      security:
        - fitbitOAuth:
            - respiratory_rate
  /1/user/{user-id}/br/date/{start-date}/{end-date}.json:
    get:
      operationId: breathingRateGetGetBreathingRateSummaryByInterval1UserUserIdBrDateStartDateEndDateJson
      summary: Get Breathing Rate Summary by Interval
      description: |-
        This endpoint returns average breathing rate data for a date range. Breathing Rate data applies specifically to a user’s “main sleep,” which is the longest single period of time during which they were asleep on a given date.

        The single date measurements are provided at the end of a period of sleep. The data returned can and often does reflect a sleep period that began the day before. For example, if you request a daily breathing rate for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user started to sleep.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Breathing-Rate
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/breathing-rate/get-br-summary-by-interval/
      security:
        - fitbitOAuth:
            - respiratory_rate
  /1/user/{user-id}/cardioscore/date/{date}.json:
    get:
      operationId: cardioFitnessScoreGetGetVo2MaxSummaryByDate1UserUserIdCardioscoreDateDateJson
      summary: Get VO2 Max Summary by Date
      description: |-
        This endpoint returns the Cardio Fitness Score (also known as VO2 Max) data for a single date. VO2 Max values will be shown as a range if no run data is available or a single numeric value if the user uses a GPS for runs. See Additional Information for further context.

        The endpoint response ignores the Units header. The value returned is always in ml/kg/min.
      tags:
        - Cardio-Fitness-Score
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/cardio-fitness-score/get-vo2max-summary-by-date/
      security:
        - fitbitOAuth:
            - cardio_fitness
  /1/user/{user-id}/cardioscore/date/{start-date}/{end-date}.json:
    get:
      operationId: cardioFitnessScoreGetGetVo2MaxSummaryByInterval1UserUserIdCardioscoreDateStartDateEndDateJson
      summary: Get VO2 Max Summary by Interval
      description: |-
        This endpoint returns the Cardio Fitness Score (also know as VO2 Max) data for a date range. VO2 Max values will be shown as a range if no run data is available or a single numeric value if the user uses a GPS for runs. See Additional Information for further context.

        The endpoint response ignores the Units header. The value returned is always in ml/kg/min.
      tags:
        - Cardio-Fitness-Score
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/cardio-fitness-score/get-vo2max-summary-by-interval/
      security:
        - fitbitOAuth:
            - cardio_fitness
  /1/user/{user-id}/devices/tracker/{tracker-id}/alarms.json:
    post:
      operationId: devicesPostCreateAlarms1UserUserIdDevicesTrackerTrackerIdAlarmsJson
      summary: Create Alarms
      description: Creates an alarm for the given device. This endpoint is supported for trackers that support alarms.
      tags:
        - Devices
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/devices/create-alarm/
      security:
        - fitbitOAuth:
            - settings
    get:
      operationId: devicesGetGetAlarms1UserUserIdDevicesTrackerTrackerIdAlarmsJson
      summary: Get Alarms
      description: Retrieves the alarms enabled for a specific device. This endpoint is supported for trackers that support alarms.
      tags:
        - Devices
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/devices/get-alarms/
      security:
        - fitbitOAuth:
            - settings
  /1/user/{user-id}/devices/tracker/{tracker-id}/alarms/{alarm-id}.json:
    delete:
      operationId: devicesDeleteDeleteAlarm1UserUserIdDevicesTrackerTrackerIdAlarmsAlarmIdJson
      summary: Delete Alarm
      description: Deletes an alarm on the given device. This endpoint is supported for trackers that support alarms.
      tags:
        - Devices
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/devices/delete-alarm/
      security:
        - fitbitOAuth:
            - settings
    post:
      operationId: devicesPostUpdateAlarm1UserUserIdDevicesTrackerTrackerIdAlarmsAlarmIdJson
      summary: Update Alarm
      description: Updates an alarm on the given device. This endpoint is supported for trackers that support alarms.
      tags:
        - Devices
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/devices/update-alarm/
      security:
        - fitbitOAuth:
            - settings
  /1/user/{user-id}/devices.json:
    get:
      operationId: devicesGetGetDevices1UserUserIdDevicesJson
      summary: Get Devices
      description: Retrieves a list of Fitbit devices paired to a user's account.
      tags:
        - Devices
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/devices/get-devices/
      security:
        - fitbitOAuth:
            - settings
  /1/user/{user-id}/ecg/list.json:
    get:
      operationId: electrocardiogramGetGetEcgLogList1UserUserIdEcgListJson
      summary: Get ECG Log List
      description: |-
        This endpoint retrieves a list of the user’s Electrocardiogram (ECG) log entries before or after a given day.

        Note: The ECG API is for research use or investigational use only, and is not intended for clinical or diagnostic purposes.
      tags:
        - Electrocardiogram
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/electrocardiogram/get-ecg-log-list/
      security:
        - fitbitOAuth:
            - electrocardiogram
  /1.1/user/-/leaderboard/friends.json:
    get:
      operationId: friendsGetGetFriendsLeaderboard11UserLeaderboardFriendsJson
      summary: Get Friends Leaderboard
      description: This endpoint returns the user's friend leaderboard in the format requested using units in the unit system which corresponds to the Accept-Language header provided. This scope does not provide access to the friend's Fitbit data. Those users will need to individually consent to share their data with your application.
      tags:
        - Friends
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/friends/get-friends-leaderboard/
      security:
        - fitbitOAuth:
            - social
  /1.1/user/{user-id}/friends.json:
    get:
      operationId: friendsGetGetFriends11UserUserIdFriendsJson
      summary: Get Friends
      description: This endpoint allows the application to retrieves a list of the specified Fitbit user's friends. This scope does not provide access to the friend's Fitbit data. Those users will need to individually consent to share their data with your application.
      tags:
        - Friends
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/friends/get-friends/
      security:
        - fitbitOAuth:
            - social
  /1/user/{user-id}/activities/heart/date/{start-date}/{end-date}.json:
    get:
      operationId: heartrateTimeseriesGetGetHeartRateTimeSeriesByDateRange1UserUserIdActivitiesHeartDateStartDateEndDateJson
      summary: Get Heart Rate Time Series by Date Range
      description: Retrieves the heart rate time series data over a period of time by specifying a date range. The response will include only the daily summary values.
      tags:
        - Heartrate-Timeseries
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/heartrate-timeseries/get-heartrate-timeseries-by-date-range/
      security:
        - fitbitOAuth:
            - heartrate
  /1/user/{user-id}/hrv/date/{date}.json:
    get:
      operationId: heartrateVariabilityGetGetHrvSummaryByDate1UserUserIdHrvDateDateJson
      summary: Get HRV Summary by Date
      description: |-
        This endpoint returns the Heart Rate Variability (HRV) data for a single date. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.

        The measurement is provided at the end of a period of sleep. The data returned usually reflects a sleep period that began the day before. For example, if you request a daily HRV rate for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user fell asleep.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Heartrate-Variability
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/heartrate-variability/get-hrv-summary-by-date/
      security:
        - fitbitOAuth:
            - heartrate
  /1/user/{user-id}/hrv/date/{startDate}/{endDate}.json:
    get:
      operationId: heartrateVariabilityGetGetHrvSummaryByInterval1UserUserIdHrvDateStartdateEnddateJson
      summary: Get HRV Summary by Interval
      description: |-
        This endpoint returns the Heart Rate Variability (HRV) data for a date range. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.

        Single date measurements are provided at the end of a period of sleep. The data returned can and often does reflects a sleep period that began the day before. For example, if you request a daily HRV rate for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user fell asleep.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Heartrate-Variability
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/heartrate-variability/get-hrv-summary-by-interval/
      security:
        - fitbitOAuth:
            - heartrate
  /1/user/{user-id}/activities/{resource}/date/{date}/1d/{detail-level}.json:
    get:
      operationId: intradayGetGetActivityIntradayByDate1UserUserIdActivitiesResourceDateDate1DDetailLevelJson
      summary: Get Activity Intraday by Date
      description: |-
        This endpoint retrieves the activity intraday time series data for a given resource on a specific date or 24 hour period. Intraday support can extend the detail-level response to include 1min, 5min and 15min for Activity.

        3rd-party developers who want access to retrieve other Fitbit users’ Intraday data through the “Client” or “Server” application type should submit a request by filling out this form . A Fitbit developer’s personal Intraday data is automatically available through the “Personal” application type. You do not need to submit a request.
      tags:
        - Intraday
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/intraday/get-activity-intraday-by-date/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/{resource}/date/{start-date}/{end-date}/{detail-level}.json:
    get:
      operationId: intradayGetGetActivityIntradayByInterval1UserUserIdActivitiesResourceDateStartDateEndDateDetailLevelJson
      summary: Get Activity Intraday by Interval
      description: |-
        This endpoint retrieves the activity intraday time series data for a given resource on a specific date range for a 24 hour period. Intraday support can extend the detail-level response to include 1min, 5min and 15min for Activity.

        3rd-party developers who want access to retrieve other Fitbit users’ Intraday data through the “Client” or “Server” application type should submit a request by filling out this form . A Fitbit developer’s personal Intraday data is automatically available through the “Personal” application type. You do not need to submit a request.
      tags:
        - Intraday
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/intraday/get-activity-intraday-by-interval/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/active-zone-minutes/date/{date}/1d/{detail-level}.json:
    get:
      operationId: intradayGetGetAzmIntradayByDate1UserUserIdActivitiesActiveZoneMinutesDateDate1DDetailLevelJson
      summary: Get AZM Intraday by Date
      description: |-
        This endpoint retrieves the active zone minute (AZM) intraday time series data for a specific date or 24 hour period. Intraday support can extend the detail-level response to include 1min, 5min and 15min for Active Zone Minutes.

        3rd-party developers who want access to retrieve other Fitbit users’ Intraday data through the “Client” or “Server” application type should submit a request by filling out this form . A Fitbit developer’s personal Intraday data is automatically available through the “Personal” application type. You do not need to submit a request.
      tags:
        - Intraday
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/intraday/get-azm-intraday-by-date/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/activities/active-zone-minutes/date/{start-date}/{end-date}/{detail-level}.json:
    get:
      operationId: intradayGetGetAzmIntradayByInterval1UserUserIdActivitiesActiveZoneMinutesDateStartDateEndDateDetailLevelJson
      summary: Get AZM Intraday by Interval
      description: This endpoint retrieves the active zone minute (AZM) intraday time series data on a specific date range or 24 hour period. Intraday support can extend the detail-level response to include 1min, 5min and 15min for Active Zone Minutes. 3rd-party developers who want access to retrieve other Fitbit users’ Intraday data through the “Client” or “Server” application type should submit a request by filling out this form . A Fitbit developer’s personal Intraday data is automatically av[...]
      tags:
        - Intraday
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/intraday/get-azm-intraday-by-interval/
      security:
        - fitbitOAuth:
            - activity
  /1/user/{user-id}/br/date/{date}/all.json:
    get:
      operationId: intradayGetGetBreathingRateIntradayByDate1UserUserIdBrDateDateAllJson
      summary: Get Breathing Rate Intraday by Date
      description: |-
        This endpoint returns intraday breathing rate data for a specified date. It measures the average breathing rate throughout the day and categories your breathing rate by sleep stage. Sleep stages vary between light sleep, deep sleep, REM sleep, and full sleep.

        The single date measurements are provided at the end of a period of sleep. The data returned can and often does reflect a sleep period that began the day before. For example, if you request a daily breathing rate for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user started to sleep.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Intraday
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/intraday/get-br-intraday-by-date/
      security:
        - fitbitOAuth:
            - respiratory_rate
  /1/user/{user-id}/br/date/{start-date}/{end-date}/all.json:
    get:
      operationId: intradayGetGetBreathingRateIntradayByInterval1UserUserIdBrDateStartDateEndDateAllJson
      summary: Get Breathing Rate Intraday by Interval
      description: |-
        This endpoint returns intraday breathing rate data for a date range. It measures the average breathing rate throughout the day and categories your breathing rate by sleep stage. Sleep stages vary between light sleep, deep sleep, REM sleep, and full sleep.

        The single date measurements are provided at the end of a period of sleep. The data returned can and often does reflect a sleep period that began the day before. For example, if you request a daily breathing rate for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user started to sleep.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Intraday
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/intraday/get-br-intraday-by-interval/
      security:
        - fitbitOAuth:
            - respiratory_rate
  /1/user/{user-id}/activities/heart/date/{date}/1d/{detail-level}.json:
    get:
      operationId: intradayGetGetHeartRateIntradayByDate1UserUserIdActivitiesHeartDateDate1DDetailLevelJson
      summary: Get Heart Rate Intraday by Date
      description: |-
        This endpoint retrieves the heart rate intraday time series data on a specific date or 24 hour period. Intraday support can extend the detail-level response to include 1sec, 1min, 5min or 15min for Heart Rate.

        3rd-party developers who want access to retrieve other Fitbit users’ Intraday data through the “Client” or “Server” application type should submit a request by filling out this form . A Fitbit developer’s personal Intraday data is automatically available through the “Personal” application type. You do not need to submit a request.
      tags:
        - Intraday
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/intraday/get-heartrate-intraday-by-date/
      security:
        - fitbitOAuth:
            - heartrate
  /1/user/{user-id}/activities/heart/date/{start-date}/{end-date}/{detail-level}.json:
    get:
      operationId: intradayGetGetHeartRateIntradayByInterval1UserUserIdActivitiesHeartDateStartDateEndDateDetailLevelJson
      summary: Get Heart Rate Intraday by Interval
      description: |-
        This endpoint retrieves the heart rate intraday time series data on a specific date range for a 24 hour period. Intraday support can extend the detail-level response to include 1sec, 1min, 5min or 15min for Heart Rate.

        3rd-party developers who want access to retrieve other Fitbit users’ Intraday data through the “Client” or “Server” application type should submit a request by filling out this form . A Fitbit developer’s personal Intraday data is automatically available through the “Personal” application type. You do not need to submit a request.
      tags:
        - Intraday
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/intraday/get-heartrate-intraday-by-interval/
      security:
        - fitbitOAuth:
            - heartrate
  /1/user/{user-id}/hrv/date/{date}/all.json:
    get:
      operationId: intradayGetGetHrvIntradayByDate1UserUserIdHrvDateDateAllJson
      summary: Get HRV Intraday by Date
      description: |-
        This endpoint returns the Heart Rate Variability (HRV) intraday data for a single date. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date. It measures the HRV rate at various times and returns Root Mean Square of Successive Differences (rmssd), Low Frequency (LF), High Frequency (HF), and Coverage data for a given measurement. Rmssd measures short-term variability in your heart rate while asleep. LF and HF capture th[...]

        Single date measurements are provided at the end of a period of sleep. The data returned usually reflects a sleep period that began the day before. For example, if you request a daily HRV rate for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user fell asleep.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Intraday
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/intraday/get-hrv-intraday-by-date/
      security:
        - fitbitOAuth:
            - heartrate
  /1/user/{user-id}/hrv/date/{startDate}/{endDate}/all.json:
    get:
      operationId: intradayGetGetHrvIntradayByInterval1UserUserIdHrvDateStartdateEnddateAllJson
      summary: Get HRV Intraday by Interval
      description: |-
        This endpoint returns the Heart Rate Variability (HRV) intraday data for a date range. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date. It measures your HRV rate at various times and returns Root Mean Square of Successive Differences (rmssd), Low Frequency (LF), High Frequency (HF), and Coverage data for a given measurement. Rmssd measures short-term variability in your heart rate while asleep. LF and HF capture th[...]

        Single date measurements are provided at the end of a period of sleep. The data returned can and often does reflects a sleep period that began the day before. For example, if you request a daily HRV rate for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user fell asleep.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Intraday
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/intraday/get-hrv-intraday-by-interval/
      security:
        - fitbitOAuth:
            - heartrate
  /1/user/{user-id}/spo2/date/{date}/all.json:
    get:
      operationId: intradayGetGetSpo2IntradayByDate1UserUserIdSpo2DateDateAllJson
      summary: Get SpO2 Intraday by Date
      description: |-
        This endpoint returns the SpO2 intraday data for a single date. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date. Spo2 values are calculated on a 5-minute exponentially-moving average.

        The measurement is provided at the end of a period of sleep. The data returned usually reflects a sleep period that began the day before. For example, if you request SpO2 levels for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user fell asleep.

        The data returned includes the percentage value of SpO2 in your bloodstream and an accurate timestamp for that measurement. It also uses units that correspond to the Accept-Language header provided.
      tags:
        - Intraday
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/intraday/get-spo2-intraday-by-date/
      security:
        - fitbitOAuth:
            - oxygen_saturation
  /1/user/{user-id}/spo2/date/{start-date}/{end-date}/all.json:
    get:
      operationId: intradayGetGetSpo2IntradayByInterval1UserUserIdSpo2DateStartDateEndDateAllJson
      summary: Get SpO2 Intraday by Interval
      description: |-
        This endpoint returns the SpO2 intraday data for a specified date range. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date. Spo2 values are calculated on a 5-minute exponentially-moving average.

        The measurement is provided at the end of a period of sleep. The data returned usually reflects a sleep period that began the day before. For example, if you request SpO2 levels for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user fell asleep.

        The data returned includes the percentage value of SpO2 in your bloodstream and an accurate timestamp for that measurement. It also uses units that correspond to the Accept-Language header provided.
      tags:
        - Intraday
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/intraday/get-spo2-intraday-by-interval/
      security:
        - fitbitOAuth:
            - oxygen_saturation
  /1/user/{user-id}/irn/alerts/list.json:
    get:
      operationId: irregularRhythmNotificationsGetGetIrnAlertsList1UserUserIdIrnAlertsListJson
      summary: Get IRN Alerts List
      description: |-
        This endpoint returns a paginated list of Irregular Rhythm Notifications (IRN) alerts, as well as all of the alert tachograms. This endpoint will only return alerts that the user has read in the Fitbit app already, as that is meant as the primary entrypoint for viewing notifications.

        Note: The IRN API is for research use or investigational use only, and is not intended for clinical or diagnostic purposes.
      tags:
        - Irregular-Rhythm-Notifications
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/irregular-rhythm-notifications/get-irn-alerts-list/
      security:
        - fitbitOAuth:
            - irregular_rhythm_notifications
  /1/user/{user-id}/irn/profile.json:
    get:
      operationId: irregularRhythmNotificationsGetGetIrnProfile1UserUserIdIrnProfileJson
      summary: Get IRN Profile
      description: |-
        This endpoint returns the user state for Irregular Rhythm Notifications (IRN). The user state contains most information about the user’s current engagement with the feature, including onboarding progress and algorithm processing state.

        Note: The IRN API is for research use or investigational use only, and is not intended for clinical or diagnostic purposes.
      tags:
        - Irregular-Rhythm-Notifications
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/irregular-rhythm-notifications/get-irn-profile/
      security:
        - fitbitOAuth:
            - irregular_rhythm_notifications
  /1/user/{user-id}/foods/log/favorite/{food-id}.json:
    post:
      operationId: nutritionPostAddFavoriteFoods1UserUserIdFoodsLogFavoriteFoodIdJson
      summary: Add Favorite Foods
      description: Adds a food with the given ID to the user's list of favorite foods.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/add-favorite-foods/
      security:
        - fitbitOAuth:
            - nutrition
    delete:
      operationId: nutritionDeleteDeleteFavoriteFoods1UserUserIdFoodsLogFavoriteFoodIdJson
      summary: Delete Favorite Foods
      description: Deletes a food with the given ID from the user's list of favorite foods.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/delete-favorite-foods/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/log/goal.json:
    post:
      operationId: nutritionPostCreateFoodGoal1UserUserIdFoodsLogGoalJson
      summary: Create Food Goal
      description: Creates or updates a user's daily calorie consumption or food plan goals.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/create-food-goal/
      security:
        - fitbitOAuth:
            - nutrition
    get:
      operationId: nutritionGetGetFoodGoals1UserUserIdFoodsLogGoalJson
      summary: Get Food Goals
      description: Retrieves the user's current daily calorie consumption goal and/or food plan.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/get-food-goals/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/log.json:
    post:
      operationId: nutritionPostCreateFoodLog1UserUserIdFoodsLogJson
      summary: Create Food Log
      description: Creates a food log entry for a given day.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/create-food-log/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods.json:
    post:
      operationId: nutritionPostCreateFood1UserUserIdFoodsJson
      summary: Create Food
      description: Creates a new private food for a user.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/create-food/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/meals.json:
    post:
      operationId: nutritionPostCreateMeal1UserUserIdMealsJson
      summary: Create Meal
      description: Creates a meal with the given food.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/create-meal/
      security:
        - fitbitOAuth:
            - nutrition
    get:
      operationId: nutritionGetGetMeals1UserUserIdMealsJson
      summary: Get Meals
      description: Retrieves a list of meals created by the user from their food log.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/get-meals/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/log/water/goal.json:
    post:
      operationId: nutritionPostCreateWaterGoal1UserUserIdFoodsLogWaterGoalJson
      summary: Create Water Goal
      description: Creates or updates a user's daily water consumption goal.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/create-water-goal/
      security:
        - fitbitOAuth:
            - nutrition
    get:
      operationId: nutritionGetGetWaterGoal1UserUserIdFoodsLogWaterGoalJson
      summary: Get Water Goal
      description: Retrieves a user's daily water consumption goal.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/get-water-goal/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/log/water.json:
    post:
      operationId: nutritionPostCreateWaterLog1UserUserIdFoodsLogWaterJson
      summary: Create Water Log
      description: Create a user's water log entry.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/create-water-log/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/{food-id}.json:
    delete:
      operationId: nutritionDeleteDeleteCustomFood1UserUserIdFoodsFoodIdJson
      summary: Delete Custom Food
      description: Deletes a custom food created by the user.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/delete-custom-food/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/log/{food-log-id}.json:
    delete:
      operationId: nutritionDeleteDeleteFoodLog1UserUserIdFoodsLogFoodLogIdJson
      summary: Delete Food Log
      description: Deletes a user's food log entry using the given log ID.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/delete-food-log/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/meals/{meal-id}.json:
    delete:
      operationId: nutritionDeleteDeleteMeal1UserUserIdMealsMealIdJson
      summary: Delete Meal
      description: Deletes an existing meal of the given meal ID.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/delete-meal/
      security:
        - fitbitOAuth:
            - nutrition
    get:
      operationId: nutritionGetGetMeal1UserUserIdMealsMealIdJson
      summary: Get Meal
      description: Retrieves a single meal created by the user from their food log given the meal id.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/get-meal/
      security:
        - fitbitOAuth:
            - nutrition
    post:
      operationId: nutritionPostUpdateMeal1UserUserIdMealsMealIdJson
      summary: Update Meal
      description: Updates an existing meal with the contents of the request.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/update-meal/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/log/water/{water-log-id}.json:
    delete:
      operationId: nutritionDeleteDeleteWaterLog1UserUserIdFoodsLogWaterWaterLogIdJson
      summary: Delete Water Log
      description: Deleted a user's water log entry using the given log ID.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/delete-water-log/
      security:
        - fitbitOAuth:
            - nutrition
    post:
      operationId: nutritionPostUpdateWaterLog1UserUserIdFoodsLogWaterWaterLogIdJson
      summary: Update Water Log
      description: Updates the quantity consumed for a user's water log entry with the given Water Log ID.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/update-water-log/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/log/favorite.json:
    get:
      operationId: nutritionGetGetFavoriteFoods1UserUserIdFoodsLogFavoriteJson
      summary: Get Favorite Foods
      description: Retrieves a list of user-specific favorite consumed foods.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/get-favorite-foods/
      security:
        - fitbitOAuth:
            - nutrition
  /1/foods/locales.json:
    get:
      operationId: nutritionGetGetFoodLocales1FoodsLocalesJson
      summary: Get Food Locales
      description: Retrieves the food locales used to search, log or create food.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/get-food-locales/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/log/date/{date}.json:
    get:
      operationId: nutritionGetGetFoodLog1UserUserIdFoodsLogDateDateJson
      summary: Get Food Log
      description: Retrieves a summary of the user's food log entry for a given day.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/get-food-log/
      security:
        - fitbitOAuth:
            - nutrition
  /1/foods/units.json:
    get:
      operationId: nutritionGetGetFoodUnits1FoodsUnitsJson
      summary: Get Food Units
      description: Retrieves a list of all valid Fitbit food units in the format requested.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/get-food-units/
      security:
        - fitbitOAuth:
            - nutrition
  /1/foods/{food-id}.json:
    get:
      operationId: nutritionGetGetFood1FoodsFoodIdJson
      summary: Get Food
      description: Retrieves the details of a specific food stored in the Fitbit food database or a private food the authorized user has entered.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/get-food/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/log/frequent.json:
    get:
      operationId: nutritionGetGetFrequentFoods1UserUserIdFoodsLogFrequentJson
      summary: Get Frequent Foods
      description: Retrieves a list of user-specific frequent consumed foods.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/get-frequent-foods/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/log/recent.json:
    get:
      operationId: nutritionGetGetRecentFoods1UserUserIdFoodsLogRecentJson
      summary: Get Recent Foods
      description: Retrieves a list of user-specific recently consumed foods.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/get-recent-foods/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/log/water/date/{date}.json:
    get:
      operationId: nutritionGetGetWaterLog1UserUserIdFoodsLogWaterDateDateJson
      summary: Get Water Log
      description: Retrieves a summary and list of a user's water log entries for a given day.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/get-water-log/
      security:
        - fitbitOAuth:
            - nutrition
  /1/foods/search.json:
    get:
      operationId: nutritionGetSearchFoods1FoodsSearchJson
      summary: Search Foods
      description: Retrieves a list of public foods from the Fitbit foods database and private foods the user created in the format requested.
      tags:
        - Nutrition
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition/search-foods/
      security:
        - fitbitOAuth:
            - nutrition
  /1/user/{user-id}/foods/log/{resource}/date/{start-date}/{end-date}.json:
    get:
      operationId: nutritionTimeseriesGetGetNutritionTimeSeriesByDateRange1UserUserIdFoodsLogResourceDateStartDateEndDateJson
      summary: Get Nutrition Time Series by Date Range
      description: Retrieves the food and water consumption data for a given resource over a period of time by specifying a date range. The response will include only the daily summary values.
      tags:
        - Nutrition-Timeseries
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/nutrition-timeseries/get-nutrition-timeseries-by-date-range/
      security:
        - fitbitOAuth:
            - nutrition
  /1.2/user/{user-id}/sleep/goal.json:
    post:
      operationId: sleepPostCreateSleepGoal12UserUserIdSleepGoalJson
      summary: Create Sleep Goal
      description: Create or update a user's sleep goal.
      tags:
        - Sleep
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/sleep/create-sleep-goals/
      security:
        - fitbitOAuth:
            - sleep
    get:
      operationId: sleepGetGetSleepGoal12UserUserIdSleepGoalJson
      summary: Get Sleep Goal
      description: Returns a user's current sleep goal.
      tags:
        - Sleep
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/sleep/get-sleep-goals/
      security:
        - fitbitOAuth:
            - sleep
  /1.2/user/{user-id}/sleep.json:
    post:
      operationId: sleepPostCreateSleepLog12UserUserIdSleepJson
      summary: Create Sleep Log
      description: Creates a log entry for a sleep event and returns a response in the format requested.
      tags:
        - Sleep
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/sleep/create-sleep-log/
      security:
        - fitbitOAuth:
            - sleep
  /1.2/user/{user-id}/sleep/{log-id}.json:
    delete:
      operationId: sleepDeleteDeleteSleepLog12UserUserIdSleepLogIdJson
      summary: Delete Sleep Log
      description: Deletes a sleep log with the given log id.
      tags:
        - Sleep
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/sleep/delete-sleep-log/
      security:
        - fitbitOAuth:
            - sleep
  /1.2/user/{user-id}/sleep/date/{startDate}/{endDate}.json:
    get:
      operationId: sleepGetGetSleepLogByDateRange12UserUserIdSleepDateStartdateEnddateJson
      summary: Get Sleep Log by Date Range
      description: |-
        This endpoint returns a list of a user's sleep log entries for a date range. The data returned for either date can include a sleep period that ended that date but began on the previous date. For example, if you request a sleep log between 2021-12-22 and 2021-12-26, it may return log entries that span 2021-12-21 and 2021-12-22, as well as 2021-12-25 and 2021-12-26.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Sleep
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/sleep/get-sleep-log-by-date-range/
      security:
        - fitbitOAuth:
            - sleep
  /1.2/user/{user-id}/sleep/date/{date}.json:
    get:
      operationId: sleepGetGetSleepLogByDate12UserUserIdSleepDateDateJson
      summary: Get Sleep Log by Date
      description: |-
        This endpoint returns a list of a user's sleep log entries for a given date. The data returned can include sleep periods that began on the previous date. For example, if you request a Sleep Log for 2021-12-22, it may return a log entry that began the previous night on 2021-12-21, but ended on 2021-12-22.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Sleep
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/sleep/get-sleep-log-by-date/
      security:
        - fitbitOAuth:
            - sleep
  /1.2/user/{user-id}/sleep/list.json:
    get:
      operationId: sleepGetGetSleepLogList12UserUserIdSleepListJson
      summary: get-sleep-log-list
      description: |-
        This endpoint returns a list of a user's sleep log entries before or after a given date, and specifying offset, limit and sort order. The data returned for different dates can include sleep periods that began on the previous date. For example, a sleep log entry for 2018-10-21 may have ended that day but started the previous night on 2018-10-20.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Sleep
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/sleep/get-sleep-log-list/
      security:
        - fitbitOAuth:
            - sleep
  /1/user/{user-id}/spo2/date/{date}.json:
    get:
      operationId: spo2GetGetSpo2SummaryByDate1UserUserIdSpo2DateDateJson
      summary: Get SpO2 Summary by Date
      description: |-
        This endpoint returns the SpO2 summary data for a single date. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.

        The measurement is provided at the end of a period of sleep. The data returned usually reflects a sleep period that began the day before. For example, if you request SpO2 levels for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user fell asleep.

        The data returned includes average, minimum, and maximum SpO2 levels. It uses units that correspond to the Accept-Language header provided.
      tags:
        - Spo2
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/spo2/get-spo2-summary-by-date/
      security:
        - fitbitOAuth:
            - oxygen_saturation
  /1/user/{user-id}/spo2/date/{start-date}/{end-date}.json:
    get:
      operationId: spo2GetGetSpo2SummaryByInterval1UserUserIdSpo2DateStartDateEndDateJson
      summary: Get SpO2 Summary by Interval
      description: |-
        This endpoint returns the SpO2 summary data for a specified date range. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.

        The measurement is provided at the end of a period of sleep. The data returned usually reflects a sleep period that began the day before. For example, if you request SpO2 levels for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user fell asleep.

        The data returned includes average, minimum, and maximum SpO2 levels. It uses units that correspond to the Accept-Language header provided.
      tags:
        - Spo2
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/spo2/get-spo2-summary-by-interval/
      security:
        - fitbitOAuth:
            - oxygen_saturation
  /1/user/{user-id}/{collection-path}/apiSubscriptions/{subscription-id}.json:
    post:
      operationId: subscriptionPostCreateSubscription1UserUserIdCollectionPathApisubscriptionsSubscriptionIdJson
      summary: Create Subscription
      description: Creates a subscription to notify the application when a user has new data available. See Creating a Subscription for more information.
      tags:
        - Subscription
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/subscription/create-subscription/
      security:
        - fitbitOAuth:
            - See
    delete:
      operationId: subscriptionDeleteDeleteSubscription1UserUserIdCollectionPathApisubscriptionsSubscriptionIdJson
      summary: Delete Subscription
      description: Deletes a subscription for a specific user. See Deleting a Subscription for more information.
      tags:
        - Subscription
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/subscription/delete-subscription/
      security:
        - fitbitOAuth:
            - See
  /1/user/{user-id}/{collection-path}/apiSubscriptions.json:
    get:
      operationId: subscriptionGetGetSubscriptionList1UserUserIdCollectionPathApisubscriptionsJson
      summary: Get Subscription List
      description: Retrieves a list of subscriptions created by your application for a specific user. You can either fetch subscriptions for a specific collection or the entire list of subscriptions for the user. For best practice, make sure that your application maintains this list on your side and uses this endpoint only to periodically ensure data consistency. See Getting a List of Subscriptions for more information.
      tags:
        - Subscription
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/subscription/get-subscription-list/
      security:
        - fitbitOAuth:
            - See
  /1/user/{user-id}/temp/core/date/{date}.json:
    get:
      operationId: temperatureGetGetTemperatureCoreSummaryByDate1UserUserIdTempCoreDateDateJson
      summary: Get Temperature (Core) Summary by Date
      description: |-
        This endpoint returns the Temperature (Core) data for a single date. Temperature (Core) data applies specifically to data logged manually by the user throughout the day.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Temperature
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/temperature/get-temperature-core-summary-by-date/
      security:
        - fitbitOAuth:
            - temperature
  /1/user/{user-id}/temp/core/date/{start-date}/{end-date}.json:
    get:
      operationId: temperatureGetGetTemperatureCoreSummaryByInterval1UserUserIdTempCoreDateStartDateEndDateJson
      summary: Get Temperature (Core) Summary by Interval
      description: |-
        This endpoint returns Temperature (Core) data for a date range. Temperature (Core) data applies specifically to data logged manually by the user on a given day. It only returns a value for dates on which the Fitbit device was able to record Temperature (Core) data and the maximum date range cannot exceed 30 days.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Temperature
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/temperature/get-temperature-core-summary-by-interval/
      security:
        - fitbitOAuth:
            - temperature
  /1/user/{user-id}/temp/skin/date/{date}.json:
    get:
      operationId: temperatureGetGetTemperatureSkinSummaryByDate1UserUserIdTempSkinDateDateJson
      summary: Get Temperature (Skin) Summary by Date
      description: |-
        This endpoint returns the Temperature (Skin) data for a single date. It only returns a value for dates on which the Fitbit device was able to record Temperature (skin) data.

        Temperature (Skin) data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.

        The measurement is provided at the end of a period of sleep. The data returned usually reflects a sleep period that began the day before. For example, if you request a daily Temperature (Skin) rate for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user fell asleep.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Temperature
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/temperature/get-temperature-skin-summary-by-date/
      security:
        - fitbitOAuth:
            - temperature
  /1/user/{user-id}/temp/skin/date/{start-date}/{end-date}.json:
    get:
      operationId: temperatureGetGetTemperatureSkinSummaryByInterval1UserUserIdTempSkinDateStartDateEndDateJson
      summary: Get Temperature (Skin) Summary by Interval
      description: |-
        This endpoint returns Temperature (Skin) data for a date range. It only returns a value for dates on which the Fitbit device was able to record Temperature (skin) data and the maximum date range cannot exceed 30 days.

        Temperature (Skin) data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.

        The measurement is provided at the end of a period of sleep. The data returned usually reflects a sleep period that began the day before. For example, if you request a daily Temperature (Skin) rate for 2021-12-22, it may include measurements that were taken the previous night on 2021-12-21 when the user fell asleep.

        It uses units that correspond to the Accept-Language header provided.
      tags:
        - Temperature
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/temperature/get-temperature-skin-summary-by-interval/
      security:
        - fitbitOAuth:
            - temperature
  /1/user/{user-id}/badges.json:
    get:
      operationId: userGetGetBadges1UserUserIdBadgesJson
      summary: Get Badges
      description: Retrieves a list of the user’s badges.
      tags:
        - User
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/user/get-badges/
      security:
        - fitbitOAuth:
            - profile
  /1/user/{user-id}/profile.json:
    get:
      operationId: userGetGetProfile1UserUserIdProfileJson
      summary: Get Profile
      description: Retrieves the user's profile data.
      tags:
        - User
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/user/get-profile/
      security:
        - fitbitOAuth:
            - profile
    post:
      operationId: userPostUpdateProfile1UserUserIdProfileJson
      summary: Update Profile
      description: Modifies a user's profile data.
      tags:
        - User
      x-fitbit-doc-url: https://dev.fitbit.com/build/reference/web-api/user/update-profile/
      security:
        - fitbitOAuth:
            - profile
components:
  securitySchemes:
    fitbitOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://www.fitbit.com/oauth2/authorize
          tokenUrl: https://api.fitbit.com/oauth2/token
          scopes:
            sleep: Read and write sleep data
            activity: Read and write activity data
            heartrate: Read heart rate data
            profile: Read profile data
            weight: Read and write weight data
            nutrition: Read and write nutrition data
            settings: Read settings
            social: Read social data
            respiratory_rate: Read breathing rate data
            temperature: Read temperature data
            oxygen_saturation: Read oxygen saturation data
            cardio_fitness: Read cardio fitness data
            electrocardiogram: Read electrocardiogram data
            irregular_rhythm_notifications: Read irregular rhythm notifications data